version: '3.6'
services:
  msa-mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: koscom
      MYSQL_ROOT_PASSWORD: koscom
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
